### ISSUE TITLE
An example of implementing using actix-raft

### ISSUE THREAD

**Issue by mosuka** [railgun-rs/actix-raft#24]
Hi,
I'm considering rewrite a Go project with Rust, and I'm looking for a server implementation using actix-raft for reference.
For example, do you know an example of implementing a simple key-value store using actix-raft?

**Comment by thedodd** [comment]
Hey @mosuka. As this is pretty much a brand new crate, I'm not aware of any projects in the wild using this crate yet. There is a project which I am working on, which is what caused me to build this crate in the first place, but it is not quite ready to share yet.

I would recommend that you give an eye to the test code, particularly the fixtures which implement the `RaftStorage` & `RaftNetwork` traits; however, they were built for testing purposes, and there for do not uphold all of the normal production invariants expressed in the guide. Thought, you might be able to get pretty far based on those examples.

I have been planning on adding a full example app implementation, something dead simple. A KV store sounds like an excellent choice. We could keep the business logic ultra simple and then just put together a Kubernetes StatefulSet resource so that folks can interact with it and such.

Currently, I don't have the time to create such an example, but if you are interested in creating such an example app here, I am more than happy to help out and do some code review and such.

Thoughts?

**Comment by mosuka** [comment]
Thank you for replying. I'll read the test code and the document.
