### ISSUE TITLE
Message passing latency?

### ISSUE THREAD

**Issue by ousado** [railgun-rs/actix-raft#54]
Looking at the design of actix-raft, I wonder what the rationale for using this many individual actors is.  IIUC there are at least 10 messages involved for every client request, with metrics even more. Benchmarking actix actors I found that message passing between actors isn't _that_ cheap, and should only be used where necessary (e.g. decoupling blocking operations). 

How about making actors optional and allowing implementation of the components via simple traits (too)?

**Comment by thedodd** [comment]
@ousado not using actors / message passing would definitely be cheaper, there's no question. Well, as long as the alternative would be something along the lines of static dispatch with generic types. Even using dyn types without message passing would quite likely be faster.

**However,** it is still fast and the primary motivation behind using the actor model was for the ability to encapsulate the various behaviors into a set of mutually non-blocking tasks. Eg, I don't want the various replication streams to be blocked by another part of the system writing data to disk &c.

Achieving that level of behavioral isolation within the Rust async ecosystem requires futures, and given that many of these tasks will need to mutate internal state (as the state of the Raft cluster evolves over time), message passing immediately becomes the obvious choice. 

As the Actix ecosystem, and the Rust async ecosystem overall, continues to evolve, this project will reap those benefits as well (as long as we keep things up-to-date `:)`).

**Comment by thedodd** [comment]
Also, a move away from Actix and the actor model — we would be talking about a complete re-write. A completely different crate. If I were to do something like that, it would not be done in this project. I would just create a different project.

**Comment by thedodd** [comment]
@ousado if you have some specific suggestions for improvement, definitely let me know.

**Comment by ousado** [comment]
@thedodd I think actix is a good choice, I'm just not convinced the networking part should live in its own actor. The component for which it makes immediate sense to me, and buys a lot of flexibility, is the storage. I'm taking a look how hard it would be to replace the networking actor with a trait. 

I came across this yesterday: https://github.com/mosuka/meteora - and I'd like to build a similar thing based on actix and your crate.

**Comment by thedodd** [comment]
@ousado awesome! That's a great use case. Yea, looks like the meteora project is using the Raft implementation created by the pingcap folks. I actually created this project specifically due to lack of flexibility of that Raft implementation. 

The implementation here is not limited by a `tick` operation. It is fully reactive based on events which actually happen in the system. This implementation does use timers, of course. For sending health check RPCs to peers and the like. However it is fully event driven. Not driven by a central `tick` operation. Also, as part of that fact, this project us fully async. That implementation is not.

Anyway @ousado, as far as the network interface not being an actor, perhaps we could do that, but we will have to ensure that it would still be able to satisfy all of the requirements incumbent upon that type. Given that the network interface will quite likely be building connections to peers and keeping them open, probably even handling reconnects, internal state mutation will be required. The actor model makes this sort of logic MUCH easier. No locking required.

Either way, definitely feel free to experiment `:)`. I'm happy to explore other patterns as we move forward.

**Comment by thedodd** [comment]
@ousado hey there. Heads-up, lots of changes coming in as part of #59. Almost all of the message passing has been removed (as everything is now based squarely on tokio).
