### ISSUE TITLE
in Metrics,if index>applied and join=true,is it normal state? thanks.

### ISSUE THREAD

**Issue by ryanjackgit** [railgun-rs/actix-raft#55]
Metrics: node=3473232121428402785 state=Leader leader=Some(3473232121428402785) term=1 index=24 applied=20 cfg={join=true members=[3473232121428402785, 7220731670040962359, 7003206518656558438] non_voters=[] removing=[7003206518656558438]}

**Comment by thedodd** [comment]
Hmm @ryanjackgit I don't see any problems with that based on an initial evaluation. Index>applied is almost always going to be the case in an active cluster. The leader will not apply until it receives confirmation that a majority of members have applied.

It is `join=true` because there is a member being removed, so the cluster is in joint consensus. Do you see an issue or unexpected behavior?

**Comment by ryanjackgit** [comment]
don't any see unexpected behavior.but this keep a long time until another node join the cluster,my test project github address: [https://github.com/ryanjackgit/sand](url)

**Comment by thedodd** [comment]
@ryanjackgit does it stay in that state indefinitely, and only finishes removal of the node one a new node has been added? Pretty sure we have tests covering this exact case.

**Comment by ryanjackgit** [comment]
it stay in that state indefinitely,until other new node was added or one of nodes was removed.
I'll take a look my code again.Thanks.

**Comment by thedodd** [comment]
@ryanjackgit ok, good to know. Let's keep this issue open for a bit until we are able to add more test cases around this. Once we are able to rule out this library, then we will close this issue.

**Comment by ryanjackgit** [comment]
@thedodd ,This problem has been solved.There's  wrong with the code I wrote. Now, Need some form of PreVote.please see [https://github.com/railgun-rs/actix-raft/issues/51](url)
